id: IB77ADB5B
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:46:46.083216
last_modified: 2023-02-09 14:46:46.083306
source_metadata:
  title: 'PP: Prajñāpāramitāhṛdaya'
  language: zh
bases:
  4F10:
    base_file: 4F10.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
